[tool.poetry]
name = "pdet-fetcher"
version = "0.1.1"
description = "pdet-fetcher: Coletor de dados brutos do PDET"
authors = ["Daniel Komesu <danielkomesu@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10"
tqdm = "^4.64.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
